[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_nft_v2 = "GwuQbUd8WeBG92PC5akefN7664eYYhGExaYyjQ25XMow"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tuzin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
