[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_nft = "7RYU21hggffWcHJGA2adRD45vB6XnAabZbXpqv6XFE6S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tuzin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
